### ISSUE TITLE
Typer with `sphinx-autobuild` going on infinite loop

### ISSUE THREAD

**Issue by tasansal** [sphinx-contrib/typer#17]
Hi, I just started using `typer` on my project documentation and it's great!

During my development, I use `sphinx-autobuild` plugin to automatically re-render the documentation when I modify anything in the `/docs` folder, including the conf.py file. 

When I run `sphinx-autobuild` the docs get built and rendered correctly. However, at the end of it, it says `conf.py` was modified and the modification was `typer_render_html`.  

I noticed this is the configuration for `sphinx-contrib/typer`, however, I am just using the defaults. Is the typer extension for sphinx modifying the conf.py file to add its default parameters?

I think this is a bug, or if I am doing something wrong please let me know.

~~I tried adding the configuration manually to conf.py with default values, which works, but I don't want to specify all the defaults in the conf.py file :)~~ NVM, I was wrong, it still has the same infinite loop.

Thanks!

**Comment by tasansal** [comment]
https://groups.google.com/g/sphinx-users/c/G_Z1yQrMeTo/m/qx2ZWTGAFAAJ

maybe this is related?

**Comment by bckohan** [comment]
Hi @tasansal  - thanks for reporting this - the typer extension is not directly modifying conf.py but it is setting some configuration values to lambdas. I have not been able to reproduce this issue using the latest two versions of sphinx-autobuild on osx python 3.8 and 3.12 builds, but I've gone ahead and changed these lambdas to functions for you to see if it works.

**Please try version 0.1.12 and let me know if that fixed your issue!**

**Comment by tasansal** [comment]
Hi @bckohan 

Unfortunately didn't work. Here is the project I am working on.

https://github.com/TGSAI/segy

You can check the docs configuration under `docs/conf.py`, and the `sphinx-autodoc` can be ran by `nox -rs docs` command if you have `nox`, `poetry`, and `python` installed.

This is the trigger for the re-builds, and goes forever.

```shell
updating environment: [config changed ('typer_render_html')] 11 added, 0 changed, 0 removed
```

**Comment by bckohan** [comment]
@tasansal please see my [PR](https://github.com/TGSAI/segy/pull/31) - I think a jupyter notebook was causing this issue for you.
