### ISSUE TITLE
Allow cross-referencing

### ISSUE THREAD

**Issue by jpmckinney** [sphinx-contrib/typer#34]
For example, sphinx-click uses the existing [`program`, `option` and `envvar` roles](https://www.sphinx-doc.org/en/master/usage/domains/standard.html) to allow cross-referencing specific commands, options, etc. https://sphinx-click.readthedocs.io/en/latest/usage/#cross-referencing

At minimum, it would be great to be able to cross-reference sections created by `:make-sections:`

**Comment by bckohan** [comment]
agree!

**Comment by bckohan** [comment]
This is implemented. When you use ``:make-sections:`` you can now use the ``:typer:`` role to cross reference commands and subcommands. E.g.:

```rst
:typer:`command-subcmd1-subcmd2`
```

**Comment by jpmckinney** [comment]
Awesome, thank you!

**Comment by jpmckinney** [comment]
Hi, I left a comment on the commit about a display issue.

Another issue I'm encountering is that cross-referencing is sensitive to the order in which pages are read. If my referring pages are read before the `typer` directive is processed, then the cross-references are not resolved ("Unknown typer reference"). 

I think instead of reusing the `std` domain, this issue might be resolved by creating your own domain, like in this example: https://www.sphinx-doc.org/en/master/development/tutorials/adding_domain.html
