### ISSUE TITLE
:typer: role link text does not reflect the actual command invocation.

### ISSUE THREAD

**Issue by bckohan** [sphinx-contrib/typer#39]

**Comment by bckohan** [comment]
@jpmckinney I'm having a little bit of trouble reproducing this. Where do you see the - characters removed? In the svg/text/html, section headers or nav bars?

**Comment by jpmckinney** [comment]
Aha, it's removed in the `:typer:` ref, so if I do:

```rst
:typer:`example-my-hyphenated-subcommand`
```

Then it was displaying as "example my hyphenated subcommand"

**Comment by bckohan** [comment]
@jpmckinney thanks for your help and persistence making this software better. I think I've got the reference kinks worked out.

**Comment by jpmckinney** [comment]
No sweat :) I got references working now, but two small issues that I opened.
